spring:
  datasource:
    url: jdbc:mysql://120.78.238.34:3306/haiTest?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1060059083a
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB # 最大支持请求大小

    #配置druid的监控页面
    druid:
      aop-patterns: com.hairui.boot.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: pjh
        login-password: 123
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名规则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #配置逻辑删除字段名
  global-config:
    db-config:
      logic-delete-field: flag




#开启指标监控中的所有端点，并以web的方式暴露所有端点
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always

#分布式文件系统FDFS配置

fdfs:
  soTimeout: 150000 #socket连接超时时长
  connectTimeout: 30000 #连接tracker服务器超时时长
#  reqHost: 192.168.8.101   #nginx访问地址
#  reqPort: 80              #nginx访问端口
  thumbImage: #缩略图生成参数，可选
    width: 60
    height: 60
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 47.97.7.122:22122

Service:
  storage:
    file:
      url: http://47.97.7.122:22000

#pageHelper配置
pagehelper:
  # dialect: ①
  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式（可以不设置）
  helper-dialect: mysql
  # 上面数据库设置后，下面的设置为true不会改变上面的结果（默认为true）
  auto-dialect: true
  page-size-zero: false # ②
  reasonable: true # ③
  # 默认值为 false，该参数对使用 RowBounds 作为分页参数时有效。（一般用不着）
  offset-as-page-num: false
  # 默认值为 false，RowBounds是否进行count查询（一般用不着）
  row-bounds-with-count: false
  #params: ④
  #support-methods-arguments: 和params配合使用，具体可以看下面的讲解
  # 默认值为 false。设置为 true 时，允许在运行时根据多数据源自动识别对应方言的分页
  auto-runtime-dialect: false # ⑤
  # 与auto-runtime-dialect配合使用
  close-conn: true
  # 用于控制默认不带 count 查询的方法中，是否执行 count 查询，这里设置为true后，total会为-1
  default-count: false
  #dialect-alias: ⑥

